### ISSUE TITLE
[google api] 파일/폴더 조회

### ISSUE THREAD

**Issue by pihitpihit** [pihitpihit/contents_curator#6]
- 기능1: 지정된 경로가 있는지 확인
    - 반환
        - 경로가 존재함 : True
        - 경로가 없음 : False

- 기능2: 지정된 경로가 파일인지 혹은 폴더인지 확인
    - 반환
        - 파일: "file"
        - 폴더: "folder"
        - 없음: None

- 기능3: 지정된 파일 정보 획득
    - 반환
        - 지정된 경로가 없음 : None
        - 지정된 경로가 폴더임 : None
        - 지정된 경로가 파일임 : (name, path, hash, timestamp, isFile,)
            - isFile은 True 고정값

- 기능4: 지정된 폴더 정보 획득
    - 옵션
        - noFolder : True or *False
        - recursive : True or *False
    - 반환
        - 지정된 경로가 없음 : None
        - 지정된 경로가 폴더임 : list of (name, path, hash, timestamp, isFile)
            - 폴더 하위 항목 정보를 긁어서 list로 반환
            - noFolder 옵션이 True 이면 isFile == False 인 항목은 list 에서 제외
            - recursive 옵션이 False 이면 지정된 폴더 하위 1dept 만 파악함
            - recursive 옵션이 True 이면 지정된 폴더의 모든 하위폴더를 파악함
        - 지정된 경로가 파일임 : None

**Comment by different021** [comment]
구글 드라이브에서 폴더 트리에 대한 서비스를 제공하지 않는다.
폴더 트리를 구성하는 부분이 필요할 경우, 별도 구현 필요
